# Generated by Django 3.2.6 on 2021-12-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
